* Towards a better PhD 

** Audience

PhD students and their post-doc supervisors

** Goal


Define the role (i.e. expectations, responsibilities, rights, ...) for PhD students and their Post-Doc supervisors,
highlight the critical skills and good traits to develop:

skills: computing, writing, reading, presenting, 
underlying skills: zooming (know when to take a detailed or a higher level view).
traits: independence, initiative, 

and provide resourses to achieve those goals


** Key skills to develop 

Being able to synthesise papers/concepts/ideas/... to their esssence. This enables:
- recognising related problems, so you can take inspiration from what other people have done
- recognise limittions/weaknesses of your own methods, opening up new research problems
- comunicate your ideas. A paper and a research proposal need to be sold!

** Key thinking skills that underly everything else

  - analythical thinking (enables modular thinking and critical thinking)
  - modular thinking . thinking in patterns helps recognising logical mistakes. thinking in terms of modules and interfaces leads to scalability.
  - hierarchical thinking: different granularities of modular thinking.
  - critical thinking 

